<?php

return array (
  'name' => '我的网站',
  'beian' => '',
  'cdnurl' => '',
  'version' => '2.6.1',
  'timezone' => 'Asia/Shanghai',
  'forbiddenip' => '',
  'languages' => 
  array (
    'backend' => 'zh-cn',
    'frontend' => 'zh-cn',
  ),
  'fixedpage' => 'dashboard',
  'categorytype' => 
  array (
    'default' => '默认',
    'page' => '单页',
    'article' => '文章',
    'test' => 'Test',
  ),
  'configgroup' => 
  array (
    'basic' => '基础配置',
    'email' => '邮件配置',
    'dictionary' => '字典配置',
    'pay' => '支付配置',
    'botconfig' => '机器人配置',
    'other' => '其他设置',
    'kefu' => '客服设置',
    'wenzi' => '文字设置',
    'save' => '存储配置',
    'gxcon' => '供需配置',
  ),
  'mail_type' => '1',
  'mail_smtp_host' => 'smtp.qq.com',
  'mail_smtp_port' => '465',
  'mail_smtp_user' => '10000',
  'mail_smtp_pass' => 'password',
  'mail_verify_type' => '2',
  'mail_from' => '10000@qq.com',
  'attachmentcategory' => 
  array (
    'image' => '图片',
    'video' => '视频',
    'other' => '其他',
  ),
  'payurl' => 'https://pay.test.shiyaook.top/api/v1/order/create-transaction',
  'paytoken' => 'qwe12345',
  'deftopadv' => '<a href=\'https://t.me/i\'>TG机器人演示群组</a>',
  'deffootadv' => '<a href="tg://setlanguage?lang=zhcncc"> 【简体中文】- 语言包</a>    <a href="https://t.me/HFID111">购买广告</a>',
  'collecttoken' => '',
  'content' => '@HFID111',
  'entertype' => '2',
  'entertext' => '欢迎{nick}进群,本机器人为专属索引演示机器人,定制开发 @HFID111',
  'enterfileurl' => '/uploads/20230119/ef2f0faba913fc3f3ab12fb331dd311a.jpg',
  'enterbutton' => '',
  'enteradv' => '0',
  'timeadv' => '3600',
  'lenght' => '20',
  'keyword' => '',
  'rate' => '7.35',
  'toptext' => '[广告]',
  'findshop' => '⚱️找商品',
  'findshopurl' => 'https://t.me/HFID111',
  'uppage' => '上一页',
  'nextpage' => '下一页',
  'wyzq' => '⚱️ 我要赚钱',
  'wyzqurl' => 'https://t.me/HFID111',
  'issearch' => '1',
  'prigroups' => '1',
  'advother' => '广告 <a href="https://t.me/HFID111">开发定制同款机器人</a>',
  'cachetime' => '3600',
  'blocktime' => '3600',
  'tgkf1' => 'https://t.me/HFID111',
  'tgkf2' => 'https://t.me/HFID111',
  'otherdata' => '请勿操作他人数据',
  'nullfunctionspage' => '没有找到该功能页面,建议联系管理员更改',
  'returnhome' => '返回首页',
  'retnrunuppage' => '返回上一页',
  'defweladv' => '@HFID111- 这是默认的进群广告',
  'timetasktoken' => '6786795549:AAGcK3A2sqpPQw2_zqBG6Zu1QIC3MlWVRLA',
  'deftimetaskadv' => '<strong>本系统严禁违法使用,仅供学习研究使用哦!</strong>
<strong>购买系统l联系TG:@HFID111</strong>
<strong>机器人定制开发 @HFID111</strong>
<strong>工作时间:19:00---24:00</strong>
<strong>演示地址:.c</strong>
<strong>演示用户名:test</strong>
<strong>演示密码:123456</strong>
<strong>机器人定制开发 @HFID111</strong>
<strong>自助搭建教程htt</strong>
<strong>每天19点才会自动发送本消息</strong>',
  'myadv' => '我的广告',
  'advtypetext' => '广告类型',
  'advtypemoney' => '广告金额',
  'buyadv' => '立即购买',
  'crateordererror' => '订单创建失败',
  'crateordersuccess' => '订单创建成功',
  'advcontent' => '广告内容',
  'linkadd' => '链接地址',
  'endtime' => '到期时间',
  'advtypename' => '所属类型',
  'buymoney' => '购买金额',
  'renewaladv' => '续费广告',
  'editadv' => '编辑广告',
  'actioneditadv' => '您正在编辑的广告如下:',
  'clickcopy' => '点击复制格式',
  'copycontent' => '这是一个测试广告|https://www.baidu.com',
  'plaseadvcontent' => '请复制上面格式回复广告内容',
  'botusername' => 'index_test001bot',
  'noadminmsg' => '请将机器人拉进群组或频道并给予管理员权限后再提交',
  'topadvdefcon' => '这是置顶的广告内容',
  'topadvdefcontime' => '3600',
  'bili' => '10',
  'membertop' => '✨✨✨✨✨账户信息✨✨✨✨✨',
  'memberusername' => '用户名',
  'membermoney' => '余额',
  'membercoin' => '宜搜币',
  'memberlink' => '推广链接',
  'memberrech' => '充值',
  'membertx' => '提现',
  'memberdh' => '兑换',
  'memberyemx' => '余额明细',
  'memberjfmx' => '宜搜币明细',
  'membersafe' => '账户安全',
  'memberdhbl' => '当前兑换比例',
  'memberrechmoney' => '请回复需要充值的金额',
  'txje' => '请回复您需要提现的金额',
  'cashsx' => '0.03',
  'settoken' => '请回复您的提现钱包token',
  'newmember' => '2',
  'hfkeyword' => '请回复您的标签,每个标签以小写逗号隔开,最多不超过5个',
  'adminlink' => '0',
  'isadmin' => '0',
  'least' => '10',
  'nogroup' => '暂未搜索到相关群组喔',
  'addmoney' => '10',
  's3ak' => 'AKIAYM6CXGJEAD45S4UM',
  's3sk' => 'AKIAYM6CXGJEAD45S4UM',
  'bucket' => 'datafilenew',
  'supply' => '10',
  'gxgroupid' => '-1001854716442',
  'gxgroupuser' => 'testltgroup',
  'gxtext' => '',
  'gxbutton' => '',
);
