#!/usr/bin/env php
<?php
namespace think;

// 命令行入口文件
// 加载基础文件
require __DIR__ . '/vendor/autoload.php';
define("API_DOMAIN","http://admin.hyperindex.tk");
//api域名
define("API_URL",API_DOMAIN."/api");
// 应用初始化
(new App())->console->run();

